# https://travis-ci.org/HearthSim/python-hsreplay
sudo: false
language: python
python: "3.6"

env:
  - TOXENV=py36
  - TOXENV=flake8

cache:
  directories:
    - $HOME/.cache/pip
    - $TRAVIS_BUILD_DIR/.tox

install:
  - pip install tox

script:
  - tox

notifications:
  email:
    on_failure: always
    on_success: change
